### ISSUE TITLE
How can I create List from code?

### ISSUE THREAD

**Issue by fpsantos86** [Happi-cat/Untech.SharePoint#16]
How can I create List from code with untech.sharepoint?

In the Client Side, please.

**Comment by KatzuoOgust** [comment]
@fpsantos86  there is no way to do that using only untech.sharepoint.
that's an ORM so it was designed not for list creation but for data fetching.
In order to create list u should use CSOM/SSOM directly

**Comment by fpsantos86** [comment]
Thanks... I have already resolved with CSOM
